// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC2RO6iU0d3nlY90QQed_ttKNqLelcNSI',
    appId: '1:265891055955:web:705370f5b017cd8247f9a6',
    messagingSenderId: '265891055955',
    projectId: 'football-pool-7a153',
    authDomain: 'football-pool-7a153.firebaseapp.com',
    storageBucket: 'football-pool-7a153.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdWUy2-Hs0ayLDm5avUhs5FaCIlMUfCV8',
    appId: '1:265891055955:android:218609353f8e9fa247f9a6',
    messagingSenderId: '265891055955',
    projectId: 'football-pool-7a153',
    storageBucket: 'football-pool-7a153.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIwTjizSXi7gAPEjH34bkXB30C7QohMc0',
    appId: '1:265891055955:ios:570dc5f553dcd88447f9a6',
    messagingSenderId: '265891055955',
    projectId: 'football-pool-7a153',
    storageBucket: 'football-pool-7a153.firebasestorage.app',
    iosBundleId: 'com.example.footballPool',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIwTjizSXi7gAPEjH34bkXB30C7QohMc0',
    appId: '1:265891055955:ios:570dc5f553dcd88447f9a6',
    messagingSenderId: '265891055955',
    projectId: 'football-pool-7a153',
    storageBucket: 'football-pool-7a153.firebasestorage.app',
    iosBundleId: 'com.example.footballPool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC2RO6iU0d3nlY90QQed_ttKNqLelcNSI',
    appId: '1:265891055955:web:c2db7504800fc19547f9a6',
    messagingSenderId: '265891055955',
    projectId: 'football-pool-7a153',
    authDomain: 'football-pool-7a153.firebaseapp.com',
    storageBucket: 'football-pool-7a153.firebasestorage.app',
  );
}
