import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import 'firebase_options.dart'; // generated by `flutterfire configure`
import 'screens/login_screen.dart';
import 'screens/pools_screen.dart';
import 'services/auth_service.dart';
import 'services/picks_service.dart';
import 'services/pool_service.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const FootballPoolApp());
}

class FootballPoolApp extends StatelessWidget {
  const FootballPoolApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        Provider(create: (_) => AuthService()),
        Provider(create: (_) => PoolService()),
        Provider(create: (_) => PicksService()),
      ],
      child: MaterialApp(
        title: 'Football Pool',
        theme: ThemeData(colorSchemeSeed: Colors.green, useMaterial3: true),
        home: const _AuthGate(),
      ),
    );
  }
}

class _AuthGate extends StatelessWidget {
  const _AuthGate();

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: context.read<AuthService>().authStateChanges,
      builder: (context, snap) {
        if (snap.connectionState == ConnectionState.waiting) {
          return const Scaffold(body: Center(child: CircularProgressIndicator()));
        }
        return snap.hasData ? const PoolsScreen() : const LoginScreen();
      },
    );
  }
}
